---
greeting-sentence: I'm in Ha Noi. It is very beautiful in the summer
spring
  datasource
    url: jdbc:mysql://localhost:3306/quicksort?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
