---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: vietnam
server:
  port: 8010  
eureka:
  instance:
    hostname: eurekahost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    
